tpnsdatabase:
  build: ../database/postgres
  container_name: tpnsdatabase
  ports:
  - "5432:5432"
  environment:
    POSTGRES_PASSWORD: 123456
    TPNS_PASS: tpns
tpnsappserver:
  build: ../applicationserver/wildfly
  container_name: tpnsappserver
  ports:
  - "8080:8080"
  links:
  - tpnsdatabase:postgres